version: "3.8"

services:


   discovery-service:
      container_name: discovery-service
      build: ./discovery-service
      ports:
        - '8761:8761'
      expose:
        - '8761'
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
        interval: 10s


   config-service:
      container_name: config-service
      build: ./config-service
      ports:
        - '9990:9990'
      expose:
        - '9990'
      environment:
        - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      depends_on:
         discovery-service:
             condition: service_healthy
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:9990/actuator/health" ]
        interval: 10s


#   customer-service:
#      build: ./customer-service
#      container_name: customer-service
#      ports:
#        - '8081:8081'
#      expose:
#        - '8081'
#      environment:
#        - CONFIG_SERVICE_URL=http://config-service:9990
#        - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
#      depends_on:
#        config-service :
#          condition: service_healthy
#
#
#   gateway-service:
#       build: ./gateway-service
#       container_name: gateway-service
#       ports:
#         - '8888:8888'
#       expose:
#         - '8888'
#       environment:
#         - CONFIG_SERVICE_URL=http://config-service:9990
#         - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
#       depends_on:
#         config-service:
#           condition: service_healthy